FROM nginx:1.27-alpine

WORKDIR /usr/share/nginx/html

COPY nginx.render.conf /etc/nginx/conf.d/default.conf
COPY index.html /usr/share/nginx/html/index.html
COPY docx.min.js /usr/share/nginx/html/docx.min.js
COPY html2pdf.bundle.min.js /usr/share/nginx/html/html2pdf.bundle.min.js

EXPOSE 80
